services:
    db:
        image: postgres:latest
        container_name: postgres_db
        restart: always
        environment:
            POSTGRES_USER: anhquan
            POSTGRES_PASSWORD: anhquandeptrai
            POSTGRES_DB: graprag
        ports:
            - "5433:5432"
        volumes:
            - postgres_data:/var/lib/postgresql

    chroma:
        image: chromadb/chroma:latest
        container_name: chroma_db
        restart: always
        command: ["run", "--host", "0.0.0.0", "--port", "8000", "--path", "/data"]
        ports:
            - "8002:8000"
        volumes:
            - ./data/chroma:/data

volumes:
    postgres_data:
